name: 'transport_scorecard'
version: '1.0.0'
config-version: 2

profile: 'transport'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  transport_scorecard:
    # Staging - views transitoires
    staging:
      +materialized: view
      +schema: staging

    # Core - tables physiques
    core:
      +materialized: table
      +schema: core
      dimensions:
        +materialized: table
      facts:
        +materialized: incremental
        +on_schema_change: "append_new_columns"
        +incremental_strategy: "insert_overwrite"
        +partition_by:
          field: "date"
          data_type: "date"
          granularity: "day"

    # Marts - tables optimisées pour BI
    marts:
      +materialized: table
      +schema: analytics
      business:
        +materialized: table
      monitoring:
        +materialized: table

vars:
  # Dates de référence pour développement
  dev_start_date: '2024-01-01'
  dev_end_date: '2024-12-31'

# temporary override to disable all models during development v1
models:
  transport_scorecard:
    staging:
      stg_validations_rail_daily:
        +enabled: false
      stg_punctuality_monthly:
        +enabled: false
      stg_ref_stop_lines:
        +enabled: false
    core:
      fct_validations_daily:
        +enabled: false
      fct_punctuality_monthly:
        +enabled: false
      dim_ticket_type:
        +enabled: false
      dim_date:
        +enabled: false
    marts:
      mart_network_scorecard_monthly:
        +enabled: false
      monitoring:
        +enabled: false
