name: 'transport_scorecard'
version: '1.0.0'
config-version: 2

profile: 'transport'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# FIX V2: merged two 'models:' blocks that existed in V1.
# YAML silently ignores the first block when two keys are identical at the same level —
# meaning all materialization config (view, table, incremental) was overridden
# by the disabled-models block, and only the +enabled: false settings were applied.
models:
  transport_scorecard:

    # --- Materialization config ---
    # Staging: lightweight views, no storage cost, always fresh
    staging:
      +materialized: view
      +schema: staging

    # Core: physical tables for dimensions and facts
    core:
      +materialized: table
      +schema: core
      dimensions:
        +materialized: table
      facts:
        +materialized: incremental
        +on_schema_change: "append_new_columns"
        +incremental_strategy: "insert_overwrite"
        +partition_by:
          field: "date"
          data_type: "date"
          granularity: "day"

    # Marts: BI-ready tables (analytics + monitoring)
    marts:
      +materialized: table
      +schema: analytics
      business:
        +materialized: table
      monitoring:
        +materialized: table

vars:
  dev_start_date: '2024-01-01'
  dev_end_date: '2024-12-31'
