transport:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: transport_staging_dev
      threads: 4
      timeout_seconds: 300
      location: europe-west1

    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_STAGING', 'transport_staging') }}"
      location: europe-west1
      threads: 8
      timeout_seconds: 600
      priority: interactive

elementary:
  outputs:
    default:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_STAGING', 'transport_staging') }}_elementary"
      threads: 8
      location: europe-west1
